### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by GEkuL** [rh-id/a-personal-stuff#4]
It would be great to add backup and restore functionality into the app, so I could transfer my data between phones.

**Comment by rh-id** [comment]
Hi this feature is added on latest release

**Comment by BrunoVitorge** [comment]
Hi, I really appreciate the aps. 
But it crash when I try to export the data.
There is the log file.
Could you help me please.

2026-07-25 21:59:23.882 main I/m.co.rh.id.a_personal_stuff.settings.ui.page.LogPage: Fichier journal supprimé
2026-07-25 21:59:31.223 main E/MainApplication: App crash: Attempt to invoke virtual method 'boolean io.reactivex.rxjava3.disposables.CompositeDisposable.add(io.reactivex.rxjava3.disposables.Disposable)' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.reactivex.rxjava3.disposables.CompositeDisposable.add(io.reactivex.rxjava3.disposables.Disposable)' on a null object reference
	at m.co.rh.id.a_personal_stuff.app.ui.page.HomePage.doExport(HomePage.java:244)
	at m.co.rh.id.a_personal_stuff.app.ui.page.HomePage.onClick(HomePage.java:236)
	at android.view.View.performClick(View.java:7600)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1345)
	at android.view.View.performClickInternal(View.java:7577)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30186)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
2026-07-25 21:59:31.241 main D/m.co.rh.id.a_personal_stuff.base.provider.BaseProviderModule: ExecutorService shutdown? true
