### ISSUE TITLE
App crashes on Barcode scan 

### ISSUE THREAD

**Issue by amarradi** [rh-id/a-personal-stuff#7]
2022-11-22 12:39:39.342 main E/MainApplication: App crash: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableTake$TakeObserver.onNext(ObservableTake.java:64)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV.updateScanResult(ItemListSV.java:335)
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV.lambda$onClick$3b38a403$1$m-co-rh-id-a_personal_stuff-app-ui-component-item-ItemListSV(ItemListSV.java:317)
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV$$ExternalSyntheticLambda13.onPop(Unknown Source:2)
	at m.co.rh.id.anavigator.Navigator.popStack(Navigator.java:982)
	at m.co.rh.id.anavigator.Navigator.popInternal(Navigator.java:254)
	at m.co.rh.id.anavigator.Navigator.popInternal(Navigator.java:227)
	at m.co.rh.id.anavigator.Navigator.pop(Navigator.java:223)
	at m.co.rh.id.a_personal_stuff.barcode.ui.ScanBarcodePage.lambda$createView$1$m-co-rh-id-a_personal_stuff-barcode-ui-ScanBarcodePage(ScanBarcodePage.java:112)
	at m.co.rh.id.a_personal_stuff.barcode.ui.ScanBarcodePage$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 11 more
2022-11-22 12:39:39.359 main D/m.co.rh.id.a_personal_stuff.base.provider.BaseProviderModule: ExecutorService shutdown? true
2022-11-22 12:39:39.360 main D/m.co.rh.id.a_personal_stuff.base.provider.BaseProviderModule: ScheduledExecutorService shutdown? true
2022-11-22 12:39:53.194 main E/MainApplication: App crash: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableTake$TakeObserver.onNext(ObservableTake.java:64)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV.updateScanResult(ItemListSV.java:335)
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV.lambda$onClick$3b38a403$1$m-co-rh-id-a_personal_stuff-app-ui-component-item-ItemListSV(ItemListSV.java:317)
	at m.co.rh.id.a_personal_stuff.app.ui.component.item.ItemListSV$$ExternalSyntheticLambda13.onPop(Unknown Source:2)
	at m.co.rh.id.anavigator.Navigator.popStack(Navigator.java:982)
	at m.co.rh.id.anavigator.Navigator.popInternal(Navigator.java:254)
	at m.co.rh.id.anavigator.Navigator.popInternal(Navigator.java:227)
	at m.co.rh.id.anavigator.Navigator.pop(Navigator.java:223)
	at m.co.rh.id.a_personal_stuff.barcode.ui.ScanBarcodePage.lambda$createView$1$m-co-rh-id-a_personal_stuff-barcode-ui-ScanBarcodePage(ScanBarcodePage.java:112)
	at m.co.rh.id.a_personal_stuff.barcode.ui.ScanBarcodePage$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 11 more
2022-11-22 12:39:53.212 main D/m.co.rh.id.a_personal_stuff.base.provider.BaseProviderModule: ExecutorService shutdown? true
2022-11-22 12:39:53.213 main D/m.co.rh.id.a_personal_stuff.base.provider.BaseProviderModule: ScheduledExecutorService shutdown? true

**Comment by rh-id** [comment]
Any picture of what it is that was being scan?

**Comment by amarradi** [comment]
Here is a Picture of an Test

Mein Krebstagebuch  https://www.marcusradisch.de

rh-id ***@***.***> schrieb am Mi., 23. Nov. 2022, 00:29:
